services:
  youtube-bot:
    image: ilmuflone/telegram-youtube-bot:latest
    environment:
      TELEGRAM_TOKEN: "Get your token from @botfather"
      YOUTUBE_LANGUAGES: "en,it"
      YOUTUBE_COOKIES: "cookies.txt"

    volumes:
      - "./youtube_cookies.txt:/app/cookies.txt:ro"
